# Entity services registered programmatically in switch.py
# These services are available on all switch entities in this integration

turn_on:
  name: Turn On
  description: Turn on a zone, valve, or schedule with optional duration parameter
  target:
    entity:
      integration: rachio_local
      domain: switch
  fields:
    duration:
      name: Duration
      description: Duration in seconds to run the zone/valve
      required: false
      example: 600
      selector:
        number:
          min: 60
          max: 3600
          step: 60
          unit_of_measurement: seconds

turn_off:
  name: Turn Off  
  description: Turn off a zone, valve, or schedule
  target:
    entity:
      integration: rachio_local
      domain: switch

# Smart Hose Timer Program Management Services

enable_program:
  name: Enable Program
  description: Enable a Smart Hose Timer program
  fields:
    program_id:
      name: Program
      description: "Select a program sensor (entities starting with 'Program:')"
      required: true
      example: sensor.smart_hose_timer_program_morning_watering
      selector:
        entity:
          integration: rachio_local
          domain: sensor
          multiple: false

disable_program:
  name: Disable Program
  description: Disable a Smart Hose Timer program
  fields:
    program_id:
      name: Program
      description: "Select a program sensor (entities starting with 'Program:')"
      required: true
      example: sensor.smart_hose_timer_program_evening_watering
      selector:
        entity:
          integration: rachio_local
          domain: sensor
          multiple: false

update_program:
  name: Update Program
  description: "Update a Smart Hose Timer program's settings. Only include the fields you want to change. Note: Only ONE scheduling type can be used (days_of_week OR interval_days OR even_days OR odd_days)."
  fields:
    program_id:
      name: Program
      description: "Select a program sensor (entities starting with 'Program:')"
      required: true
      example: sensor.smart_hose_timer_program_morning_watering
      selector:
        entity:
          integration: rachio_local
          domain: sensor
          multiple: false
    enabled:
      name: Enabled
      description: Enable or disable the program
      required: false
      selector:
        boolean:
    name:
      name: Name
      description: Program name
      required: false
      example: "Morning Watering"
      selector:
        text:
    rain_skip_enabled:
      name: Rain Skip Enabled
      description: Enable or disable rain skip for this program
      required: false
      selector:
        boolean:
    color:
      name: Color
      description: Program color in hex format (e.g., #00A7E1)
      required: false
      example: "#00A7E1"
      selector:
        color_rgb:
    runs:
      name: Program Runs
      description: "Configure one or more runs per day with start times and valves. Provide as YAML/JSON array. Each run can have 'start_time' OR 'sun_event'+'sun_offset_minutes', plus optional 'valves' array."
      required: false
      example: '[{"start_time": "06:00", "valves": [{"entity_id": "switch.valve_1", "duration": 300}]}, {"sun_event": "AFTER_SET", "sun_offset_minutes": 30, "valves": [{"entity_id": "switch.valve_2", "duration": 200}]}]'
      selector:
        object:
    days_of_week:
      name: Days of Week
      description: "Select days when program should run (for weekly schedules). Cannot be used with interval_days, even_days, or odd_days."
      required: false
      example: ["monday", "wednesday", "friday"]
      selector:
        select:
          multiple: true
          options:
            - label: Monday
              value: "monday"
            - label: Tuesday
              value: "tuesday"
            - label: Wednesday
              value: "wednesday"
            - label: Thursday
              value: "thursday"
            - label: Friday
              value: "friday"
            - label: Saturday
              value: "saturday"
            - label: Sunday
              value: "sunday"
    interval_days:
      name: Interval Days
      description: "Number of days between runs (for interval-based schedules). Cannot be used with days_of_week, even_days, or odd_days."
      required: false
      example: 3
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: days
          mode: box
    even_days:
      name: Even Days
      description: "Run on even calendar days (e.g., 2nd, 4th, 6th). Cannot be used with days_of_week, interval_days, or odd_days."
      required: false
      selector:
        boolean:
    odd_days:
      name: Odd Days
      description: "Run on odd calendar days (e.g., 1st, 3rd, 5th). Cannot be used with days_of_week, interval_days, or even_days."
      required: false
      selector:
        boolean:
